server {
  listen 80;
  location /v1/ {
    proxy_pass http://api:8000/v1/;
  }
  location /health {
    proxy_pass http://api:8000/health;
  }
  location / {
    root /usr/share/nginx/html;
    try_files $uri /index.html;
  }
}
